// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: ws.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushResponse_PushStatus int32

const (
	PushResponse_UNKNOWN     PushResponse_PushStatus = 0
	PushResponse_PENDING     PushResponse_PushStatus = 1
	PushResponse_IN_PROGRESS PushResponse_PushStatus = 2
	PushResponse_FAILED      PushResponse_PushStatus = 3
	PushResponse_COMPLETED   PushResponse_PushStatus = 4
)

// Enum value maps for PushResponse_PushStatus.
var (
	PushResponse_PushStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "PENDING",
		2: "IN_PROGRESS",
		3: "FAILED",
		4: "COMPLETED",
	}
	PushResponse_PushStatus_value = map[string]int32{
		"UNKNOWN":     0,
		"PENDING":     1,
		"IN_PROGRESS": 2,
		"FAILED":      3,
		"COMPLETED":   4,
	}
)

func (x PushResponse_PushStatus) Enum() *PushResponse_PushStatus {
	p := new(PushResponse_PushStatus)
	*p = x
	return p
}

func (x PushResponse_PushStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushResponse_PushStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ws_proto_enumTypes[0].Descriptor()
}

func (PushResponse_PushStatus) Type() protoreflect.EnumType {
	return &file_ws_proto_enumTypes[0]
}

func (x PushResponse_PushStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushResponse_PushStatus.Descriptor instead.
func (PushResponse_PushStatus) EnumDescriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{1, 0}
}

type WebsocketMessage_MessageType int32

const (
	WebsocketMessage_UNKNOWN       WebsocketMessage_MessageType = 0
	WebsocketMessage_PUSH_REQUEST  WebsocketMessage_MessageType = 1
	WebsocketMessage_PUSH_RESPONSE WebsocketMessage_MessageType = 2
)

// Enum value maps for WebsocketMessage_MessageType.
var (
	WebsocketMessage_MessageType_name = map[int32]string{
		0: "UNKNOWN",
		1: "PUSH_REQUEST",
		2: "PUSH_RESPONSE",
	}
	WebsocketMessage_MessageType_value = map[string]int32{
		"UNKNOWN":       0,
		"PUSH_REQUEST":  1,
		"PUSH_RESPONSE": 2,
	}
)

func (x WebsocketMessage_MessageType) Enum() *WebsocketMessage_MessageType {
	p := new(WebsocketMessage_MessageType)
	*p = x
	return p
}

func (x WebsocketMessage_MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebsocketMessage_MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_ws_proto_enumTypes[1].Descriptor()
}

func (WebsocketMessage_MessageType) Type() protoreflect.EnumType {
	return &file_ws_proto_enumTypes[1]
}

func (x WebsocketMessage_MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebsocketMessage_MessageType.Descriptor instead.
func (WebsocketMessage_MessageType) EnumDescriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{2, 0}
}

type PushMessage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PushId            string                 `protobuf:"bytes,1,opt,name=push_id,json=pushId,proto3" json:"push_id,omitempty"`
	BatchFile         []byte                 `protobuf:"bytes,2,opt,name=batch_file,json=batchFile,proto3" json:"batch_file,omitempty"`
	CodeDiff          string                 `protobuf:"bytes,3,opt,name=code_diff,json=codeDiff,proto3" json:"code_diff,omitempty"`
	ChangeDescription string                 `protobuf:"bytes,4,opt,name=change_description,json=changeDescription,proto3" json:"change_description,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PushMessage) Reset() {
	*x = PushMessage{}
	mi := &file_ws_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessage) ProtoMessage() {}

func (x *PushMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessage.ProtoReflect.Descriptor instead.
func (*PushMessage) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{0}
}

func (x *PushMessage) GetPushId() string {
	if x != nil {
		return x.PushId
	}
	return ""
}

func (x *PushMessage) GetBatchFile() []byte {
	if x != nil {
		return x.BatchFile
	}
	return nil
}

func (x *PushMessage) GetCodeDiff() string {
	if x != nil {
		return x.CodeDiff
	}
	return ""
}

func (x *PushMessage) GetChangeDescription() string {
	if x != nil {
		return x.ChangeDescription
	}
	return ""
}

type PushResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Status        PushResponse_PushStatus `protobuf:"varint,1,opt,name=status,proto3,enum=PushResponse_PushStatus" json:"status,omitempty"`
	ErrorMessage  string                  `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_ws_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResponse.ProtoReflect.Descriptor instead.
func (*PushResponse) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{1}
}

func (x *PushResponse) GetStatus() PushResponse_PushStatus {
	if x != nil {
		return x.Status
	}
	return PushResponse_UNKNOWN
}

func (x *PushResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type WebsocketMessage struct {
	state       protoimpl.MessageState       `protogen:"open.v1"`
	MessageType WebsocketMessage_MessageType `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=WebsocketMessage_MessageType" json:"message_type,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*WebsocketMessage_PushMessage
	//	*WebsocketMessage_PushResponse
	Message       isWebsocketMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebsocketMessage) Reset() {
	*x = WebsocketMessage{}
	mi := &file_ws_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsocketMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketMessage) ProtoMessage() {}

func (x *WebsocketMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketMessage.ProtoReflect.Descriptor instead.
func (*WebsocketMessage) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{2}
}

func (x *WebsocketMessage) GetMessageType() WebsocketMessage_MessageType {
	if x != nil {
		return x.MessageType
	}
	return WebsocketMessage_UNKNOWN
}

func (x *WebsocketMessage) GetMessage() isWebsocketMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *WebsocketMessage) GetPushMessage() *PushMessage {
	if x != nil {
		if x, ok := x.Message.(*WebsocketMessage_PushMessage); ok {
			return x.PushMessage
		}
	}
	return nil
}

func (x *WebsocketMessage) GetPushResponse() *PushResponse {
	if x != nil {
		if x, ok := x.Message.(*WebsocketMessage_PushResponse); ok {
			return x.PushResponse
		}
	}
	return nil
}

type isWebsocketMessage_Message interface {
	isWebsocketMessage_Message()
}

type WebsocketMessage_PushMessage struct {
	PushMessage *PushMessage `protobuf:"bytes,2,opt,name=push_message,json=pushMessage,proto3,oneof"`
}

type WebsocketMessage_PushResponse struct {
	PushResponse *PushResponse `protobuf:"bytes,3,opt,name=push_response,json=pushResponse,proto3,oneof"`
}

func (*WebsocketMessage_PushMessage) isWebsocketMessage_Message() {}

func (*WebsocketMessage_PushResponse) isWebsocketMessage_Message() {}

var File_ws_proto protoreflect.FileDescriptor

const file_ws_proto_rawDesc = "" +
	"\n" +
	"\bws.proto\"\x91\x01\n" +
	"\vPushMessage\x12\x17\n" +
	"\apush_id\x18\x01 \x01(\tR\x06pushId\x12\x1d\n" +
	"\n" +
	"batch_file\x18\x02 \x01(\fR\tbatchFile\x12\x1b\n" +
	"\tcode_diff\x18\x03 \x01(\tR\bcodeDiff\x12-\n" +
	"\x12change_description\x18\x04 \x01(\tR\x11changeDescription\"\xb9\x01\n" +
	"\fPushResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.PushResponse.PushStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"R\n" +
	"\n" +
	"PushStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\x12\r\n" +
	"\tCOMPLETED\x10\x04\"\x89\x02\n" +
	"\x10WebsocketMessage\x12@\n" +
	"\fmessage_type\x18\x01 \x01(\x0e2\x1d.WebsocketMessage.MessageTypeR\vmessageType\x121\n" +
	"\fpush_message\x18\x02 \x01(\v2\f.PushMessageH\x00R\vpushMessage\x124\n" +
	"\rpush_response\x18\x03 \x01(\v2\r.PushResponseH\x00R\fpushResponse\"?\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x10\n" +
	"\fPUSH_REQUEST\x10\x01\x12\x11\n" +
	"\rPUSH_RESPONSE\x10\x02B\t\n" +
	"\amessageB,Z*github.com/bifrostinc/code-sync-sidecar/pbb\x06proto3"

var (
	file_ws_proto_rawDescOnce sync.Once
	file_ws_proto_rawDescData []byte
)

func file_ws_proto_rawDescGZIP() []byte {
	file_ws_proto_rawDescOnce.Do(func() {
		file_ws_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ws_proto_rawDesc), len(file_ws_proto_rawDesc)))
	})
	return file_ws_proto_rawDescData
}

var file_ws_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ws_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ws_proto_goTypes = []any{
	(PushResponse_PushStatus)(0),      // 0: PushResponse.PushStatus
	(WebsocketMessage_MessageType)(0), // 1: WebsocketMessage.MessageType
	(*PushMessage)(nil),               // 2: PushMessage
	(*PushResponse)(nil),              // 3: PushResponse
	(*WebsocketMessage)(nil),          // 4: WebsocketMessage
}
var file_ws_proto_depIdxs = []int32{
	0, // 0: PushResponse.status:type_name -> PushResponse.PushStatus
	1, // 1: WebsocketMessage.message_type:type_name -> WebsocketMessage.MessageType
	2, // 2: WebsocketMessage.push_message:type_name -> PushMessage
	3, // 3: WebsocketMessage.push_response:type_name -> PushResponse
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ws_proto_init() }
func file_ws_proto_init() {
	if File_ws_proto != nil {
		return
	}
	file_ws_proto_msgTypes[2].OneofWrappers = []any{
		(*WebsocketMessage_PushMessage)(nil),
		(*WebsocketMessage_PushResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ws_proto_rawDesc), len(file_ws_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ws_proto_goTypes,
		DependencyIndexes: file_ws_proto_depIdxs,
		EnumInfos:         file_ws_proto_enumTypes,
		MessageInfos:      file_ws_proto_msgTypes,
	}.Build()
	File_ws_proto = out.File
	file_ws_proto_goTypes = nil
	file_ws_proto_depIdxs = nil
}
