name: Go Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "code-sync-sidecar/go.mod"

      - name: Test
        working-directory: ./code-sync-sidecar
        run: go test ./...
